### PR TITLE
Article voting buttons

### PR DESCRIPTION
**Pull request by patrickarigg**
adds voting buttons with optimistic rendering and warning to user if the API request fails

### CODE REVIEW

**Comment by nc-saleh** [comment]
Some great work here Patrick! I have a single comment: 

 - if something goes wrong with the patching of the vote, we should be giving the user some kind of message! Please amend this and resubmit an nchelp pr

**Comment by patrickarigg** [comment]
There is a catch block in Article.jsx on line 29 that handles this. The vote render optimistically then are reset back to their previous state if the request fails. If there is an error a p tag renders with an error message for 2 seconds.

**Comment by patrickarigg** [comment]
Now fixed - was handling error in api.js instead of Article.jsx

**Review by nc-nick-jones — APPROVED** [review]
crackin stuff patrick

**Pull request merged**
